### ISSUE TITLE
reunião dia 12/03/2020

### ISSUE THREAD

**Issue by Athospd** [curso-r/stn-caixa#7]
## Roteiro

- app explorador v3
- indicadores - descricao (relatorio)
- relatorio a terminar (não tem indicador xgboost)
- scripts 01 - 07
- sobre o modelo xgboost (var Imp, etc)
- app rotulador está falho
- feedbacks stn
- proximos passos

## TODO - Rotulador
- dados persistentes (googlesheets)
- multiple tags + criar tag ao vivo

## TODO - Modelo Preditivo
- [ ] medir os tempos positivos dentro da mesma série (e depois poder tirar o máximo, o N etc)
- [ ] crescimento no ultimo mes

## TODO - Explorador
- [ ] colocar o histórico como parâmetro na tela.
- [ ] NO_UG e NO_FONTE na tooltip da bolinha do grafico de dispersao
- [ ] colocar as demais series temporais: obrigacoes, pagamentos e saldo_diario(caixa)

## Misc
- criar slides além do relatório
- Estudar as pessoas que: tem obrigacoes a pagar (ja ta liquidado) e tem suficiencia de caixa, mas por alguma razao nao pagou.
